config/routes.rb
Rails.application.routes.draw do
  resources :debugs
  devise_for :admins, path_names: {
  sign_up: ''
}
  resources :contracts
  resources :quests
  resources :items
  resources :clues
  resources :teams
  resources :properties

  root 'teams#index'
  get '/sms_log' => "teams#generate_sms_log", as: 'sms_log'
  get '/pick_r' => "teams#pick_random_rosarian", as: 'pick_r'
  get '/pick_l' => "teams#pick_random_lamplighter", as: 'pick_l'
  patch '/send_rs' => "teams#send_rosarians_message", as: 'send_rs'
  patch '/send_ls' => "teams#send_lamplighters_message", as: 'send_ls'
  patch '/payout' => "teams#payout", as: 'payout'
  patch '/send_message/:id' => "teams#send_message", as: 'send_message'
  patch '/buy_prop/:id' => "teams#buy_property", as: 'buy_prop'
  patch '/get_contract/:id' => "teams#get_contract", as: 'get_contract'
  patch '/get_clue/:id' => "teams#get_clue", as: 'get_clue'
  patch '/recieve_quest/:id' => "teams#recieve_quest", as: 'recieve_quest'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quest.rb
class Quest < ApplicationRecord
  has_many :recieved_quests
  before_create :set_defaults
  before_destroy :sever_connections
  validates :quest_name, :description, :day, :quest_type, presence: true

  def day_to_string
    case self.day
    when 1
      "The Terrible Business of Theodore Humphreys"
    when 2
      "A Trial for Ann"
    when 3
      "The Civil Institution"
    end
  end

  def format_output
    output = ""
    if self.money_output!=0
      output+="Money: #{self.money_output}£ "
    end
    if self.inf_output!=0
      output+="#{inf_type} Infomration: #{self.inf_output} " #
    end
    if self.clue_output!=0
      output+="Clue: #{Clue.find(self.clue_output).name} "
    end
    if self.item_output!=0
      output+="Item: #{Item.find(self.item_output).name} "
    end
    output
  end

  def convert_type_to_int
    case self.inf_type
    when "Public"
      0
    when "Market"
      1
    when "Seedy"
      2
    when "Royal"
      3
    end
  end


private

  def set_defaults
    self.money_output = 0 if self.money_output.nil?
    self.inf_output = 0 if self.inf_output.nil?
    self.clue_output = 0 if self.clue_output.nil?
    self.item_output = 0 if self.item_output.nil?
    self.notes = "" if self.notes.nil?
  end

  def sever_connections
    RecievedQuest.where(quest_id: self.id).destroy_all
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  load_and_authorize_resource

  # GET /quests
  # GET /quests.json
  def index
    @quests = Quest.all

    unless params["search"].nil?
      case params["search"]
      when "main"
        @quests=Quest.where(quest_type: "Main")
      when "item"
        @quests=Quest.where(quest_type: "Item")
      when "side"
        @quests=Quest.where(quest_type: "Side")
      when "cash"
        @quests=Quest.where(quest_type: "Cash")
      end
    end
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests
  # POST /quests.json
  def create
    @quest = Quest.new(quest_params)
    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quests/1
  # PATCH/PUT /quests/1.json
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
        format.json { render :show, status: :ok, location: @quest }
      else
        format.html { render :edit }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.json
  def destroy
    @quest.destroy
    respond_to do |format|
      format.html { redirect_to quests_url, notice: 'Quest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quest_params
      params.require(:quest).permit(:quest_name, :description, :req, :day, :quest_type, :money_output, :inf_type, :inf_output, :clue_output, :item_output, :notes, :dependent_on, :unlocks)
    end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<%= form_for(quest) do |f| %>
  <% if quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
      <% quest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quest_name %>
    <%= f.text_field :quest_name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :req %>
    <%= f.text_area :req %>
  </div>

  <div class="field">
    <%= f.label :day %>
    <%= f.select :day, [1,2,3] %>
  </div>

  <div class="field">
    <%= f.label :quest_type %>
    <%= f.select :quest_type, ["Main", "Item", "Side", "Cash"] %>
  </div>

  <div class="field">
    <%= f.label :money_output %>
    <%= f.number_field :money_output %>
  </div>

  <div class="field">
    <%= f.label :resource_type %>
    <%= f.select :inf_type, ["Public", "Market", "Seedy", "Royal"] %>
  </div>

  <div class="field">
    <%= f.label :resource_output %>
    <%= f.number_field :inf_output %>
  </div>

  <div class="field">
    <%= f.label :clue_output %>
    <%= f.select :clue_output, Clue.all.collect{|c| [c.name, c.id]}, {:include_blank => true} %>
  </div>

  <div class="field">
    <%= f.label :item_output %>
    <%= f.select :item_output,  [0]+Item.all.collect{|c| c.id} %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quests/edit.html.erb
<h1>Editing Quest</h1>

<%= render 'form', quest: @quest %>

<%= link_to 'Show', @quest %> |
<%= link_to 'Back', quests_path %>

app/views/quests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quests</h1>
<div style="display: inline-flex">
  <%= button_to 'New Quest', new_quest_path, method: :get %>
  <%= form_tag({:action => "index"}, {:method => :get}) do %>
  <%= hidden_field_tag(:search, "main") %>
  <div class="">
    <%= submit_tag 'Show Only Main Quests' %>
  </div>
  <% end %>
  <%= form_tag({:action => "index"}, {:method => :get}) do %>
  <%= hidden_field_tag(:search, "item") %>
  <div class="">
    <%= submit_tag 'Show Only Item Quests' %>
  </div>
  <% end %>
  <%= form_tag({:action => "index"}, {:method => :get}) do %>
  <%= hidden_field_tag(:search, "side") %>
  <div class="">
    <%= submit_tag 'Show Only Side Quests' %>
  </div>
  <% end %>
  <%= form_tag({:action => "index"}, {:method => :get}) do %>
  <%= hidden_field_tag(:search, "cash") %>
  <div class="">
    <%= submit_tag 'Show Only Cash Quests' %>
  </div>
  <% end %>

</div>


<table class="table">
  <thead>
    <tr>
      <th>Quest name</th>
      <th>Description</th>
      <th>Day</th>
      <th>Quest type</th>
      <th>Money output</th>
      <th>INF output</th>
      <th>Clue output</th>
      <th>Item output</th>
      <th>Has notes?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quests.each do |quest| %>
      <tr>
        <td><%= quest.quest_name %></td>
        <td><%= quest.description %></td>
        <td><%= quest.day %></td>
        <td><%= quest.quest_type %></td>
        <td><%= quest.money_output %>£</td>
        <td><%= quest.inf_output %><span class="circle circle<%=quest.convert_type_to_int%>"></span></td>
        <td><%= quest.clue_output!=0 && !quest.clue_output.nil? ? link_to(Clue.find(quest.clue_output).name, Clue.find(quest.clue_output)) : "No Clue" %></td>
        <td><%= quest.item_output!=0 ? link_to(Item.find(quest.item_output).name, Item.find(quest.item_output)) : "No Item" %></td>
        <td><%= quest.notes.empty? ? "No notes" : "Has notes" %></td>
        <td><%= link_to 'Show', quest %></td>
        <td><%= link_to 'Edit', edit_quest_path(quest) %></td>
        <td><%= link_to 'Destroy', quest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/quests/new.html.erb
<h1>New Quest</h1>

<%= render 'form', quest: @quest %>

<%= link_to 'Back', quests_path %>

app/views/quests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quest name:</strong>
  <%= @quest.quest_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @quest.description %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @quest.req %>
</p>

<p>
  <strong>Day:</strong>
  <%= @quest.day_to_string %>
</p>

<p>
  <strong>Quest type:</strong>
  <%= @quest.quest_type %> Quest
</p>

<p>
  <strong>Money output:</strong>
  <%= @quest.money_output %>£
</p>
<p>
  <strong>Info output:</strong>
  <%= @quest.inf_output %><span class="circle circle<%=@quest.convert_type_to_int%>"></span>
</p>
<p>
  <strong>Clue output:</strong>
  <%= @quest.clue_output!=0 && !@quest.clue_output.nil? ? link_to(Clue.find(@quest.clue_output).name, Clue.find(@quest.clue_output)) : "No Clue" %>
</p>


<p>
  <strong>Item output:</strong>
  <%= @quest.item_output!=0 ? link_to(Item.find(@quest.item_output).name, Item.find(@quest.item_output)) : "No Item" %>
</p>

<p><strong>Current Teams:</strong></p>
<ul>
  <% @quest.recieved_quests.sort_by{|s| s.status}.each do |rc| %>
    <% team = Team.find(rc.team_id) %>
    <li><%=link_to "#{team.phone_num}", team%> -- <%=(rc.status==2 ? "Completed" : "In Progress") %></li>
  <% end %>
  <%= "<li>No teams have recieved this quest.</li>".html_safe if @quest.recieved_quests.sort_by{|s| s.status}.empty? %>
</ul>

<p>
  <strong>Notes:</strong>
  <%= @quest.notes %>
  <%= "No notes" if @quest.notes.empty? %>
</p>





<%= link_to 'Edit', edit_quest_path(@quest) %> |
<%= link_to 'Back', quests_path %>