config/routes.rb
Rails.application.routes.draw do
  resources :debugs
  devise_for :admins, path_names: {
  sign_up: ''
}
  resources :contracts
  resources :quests
  resources :items
  resources :clues
  resources :teams
  resources :properties

  root 'teams#index'
  get '/sms_log' => "teams#generate_sms_log", as: 'sms_log'
  get '/pick_r' => "teams#pick_random_rosarian", as: 'pick_r'
  get '/pick_l' => "teams#pick_random_lamplighter", as: 'pick_l'
  patch '/send_rs' => "teams#send_rosarians_message", as: 'send_rs'
  patch '/send_ls' => "teams#send_lamplighters_message", as: 'send_ls'
  patch '/payout' => "teams#payout", as: 'payout'
  patch '/send_message/:id' => "teams#send_message", as: 'send_message'
  patch '/buy_prop/:id' => "teams#buy_property", as: 'buy_prop'
  patch '/get_contract/:id' => "teams#get_contract", as: 'get_contract'
  patch '/get_clue/:id' => "teams#get_clue", as: 'get_clue'
  patch '/recieve_quest/:id' => "teams#recieve_quest", as: 'recieve_quest'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/debug.rb
class Debug < ApplicationRecord
end

app/controllers/debugs_controller.rb
class DebugsController < ApplicationController
  before_action :set_debug, only: [:show, :edit, :update, :destroy]

  # GET /debugs
  # GET /debugs.json
  def index
    @debugs = Debug.all
  end

  # GET /debugs/1
  # GET /debugs/1.json
  def show
  end

  # GET /debugs/new
  def new
    @debug = Debug.new
  end

  # GET /debugs/1/edit
  def edit
  end

  # POST /debugs
  # POST /debugs.json
  def create
    @debug = Debug.new(debug_params)

    respond_to do |format|
      if @debug.save
        format.html { redirect_to @debug, notice: 'Debug was successfully created.' }
        format.json { render :show, status: :created, location: @debug }
      else
        format.html { render :new }
        format.json { render json: @debug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debugs/1
  # PATCH/PUT /debugs/1.json
  def update
    respond_to do |format|
      if @debug.update(debug_params)
        format.html { redirect_to @debug, notice: 'Debug was successfully updated.' }
        format.json { render :show, status: :ok, location: @debug }
      else
        format.html { render :edit }
        format.json { render json: @debug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debugs/1
  # DELETE /debugs/1.json
  def destroy
    @debug.destroy
    respond_to do |format|
      format.html { redirect_to debugs_url, notice: 'Debug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_debug
      @debug = Debug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debug_params
      params.require(:debug).permit(:log, :user)
    end
end

app/helpers/debugs_helper.rb
module DebugsHelper
end

app/views/debugs/_form.html.erb
<%= form_for(debug) do |f| %>
  <% if debug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(debug.errors.count, "error") %> prohibited this debug from being saved:</h2>

      <ul>
      <% debug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :log %>
    <%= f.text_area :log %>
  </div>

  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/debugs/edit.html.erb
<h1>Editing Debug</h1>

<%= render 'form', debug: @debug %>

<%= link_to 'Show', @debug %> |
<%= link_to 'Back', debugs_path %>

app/views/debugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Debug Logs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Log</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @debugs.each do |debug| %>
      <tr>
        <td><%= debug.log %></td>
        <td><%= debug.user %></td>
        <td><%= link_to 'Show', debug %></td>
        <td><%= link_to 'Edit', edit_debug_path(debug) %></td>
        <td><%= link_to 'Destroy', debug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Debug', new_debug_path %>

app/views/debugs/new.html.erb
<h1>New Debug</h1>

<%= render 'form', debug: @debug %>

<%= link_to 'Back', debugs_path %>

app/views/debugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Log:</strong>
  <%= @debug.log %>
</p>

<p>
  <strong>User:</strong>
  <%= @debug.user %>
</p>


<%= link_to 'Edit', edit_debug_path(@debug) %> |
<%= link_to 'Back', debugs_path %>