config/routes.rb
Rails.application.routes.draw do
  resources :debugs
  devise_for :admins, path_names: {
  sign_up: ''
}
  resources :contracts
  resources :quests
  resources :items
  resources :clues
  resources :teams
  resources :properties

  root 'teams#index'
  get '/sms_log' => "teams#generate_sms_log", as: 'sms_log'
  get '/pick_r' => "teams#pick_random_rosarian", as: 'pick_r'
  get '/pick_l' => "teams#pick_random_lamplighter", as: 'pick_l'
  patch '/send_rs' => "teams#send_rosarians_message", as: 'send_rs'
  patch '/send_ls' => "teams#send_lamplighters_message", as: 'send_ls'
  patch '/payout' => "teams#payout", as: 'payout'
  patch '/send_message/:id' => "teams#send_message", as: 'send_message'
  patch '/buy_prop/:id' => "teams#buy_property", as: 'buy_prop'
  patch '/get_contract/:id' => "teams#get_contract", as: 'get_contract'
  patch '/get_clue/:id' => "teams#get_clue", as: 'get_clue'
  patch '/recieve_quest/:id' => "teams#recieve_quest", as: 'recieve_quest'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>London Divided Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body class="<%= @public_view ? "public" : "" %>">
    <% if !@public_view && controller_name!="sessions"  %>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand">London Divied</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="<%='active' if controller_name=='teams' && action_name!='generate_sms_log'%>"><%= link_to 'Teams', teams_path %></li>
              <% if current_admin.has_role? :admin %>
                <li class="<%='active' if controller_name=='properties' %>"> <%= link_to 'Properties', properties_path %></li>
                <li class="<%='active' if controller_name=='contracts' %>"> <%= link_to 'Contracts', contracts_path %></li>
                <li class="<%='active' if controller_name=='quests' %>"> <%= link_to 'Quests', quests_path %></li>
                <li class="<%='active' if controller_name=='clues' %>"> <%= link_to 'Clues', clues_path %></li>
              <% end %>
              <li class="<%='active' if controller_name=='items' %>"> <%= link_to 'Items', items_path %></li>
              <% if current_admin.has_role? :admin %>
                <li class="<%='active' if action_name=='generate_sms_log' %>"> <%= link_to 'SMS Log', sms_log_path %></li>
                <li class="<%='active' if controller_name=='debugs' %>"> <%= link_to 'Debug Logging', debugs_path %></li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete if current_admin %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
    <% end %>
    <div class="container">
      <%= yield %>

    </div>
  </body>
</html>